### ISSUE TITLE
视频呼叫对方时，页面显示自己的名字，应该显示对方名字吧！！

### ISSUE THREAD

**Issue by nameIsYong** [rongcloud/callkit-ios#11]
RCCallSingleCallViewController.m

- (void)resetLayout:(BOOL)isMultiCall mediaType:(RCCallMediaType)mediaType callStatus:(RCCallStatus)callStatus {
......
} else if (callStatus == RCCallDialing) {
       //这里显示的自己名字
       [self.remoteNameLabel setText:[self generateUserModel:currentUserId].userInfo.name];
     //不是应该显示对方？？
    [self.remoteNameLabel setText:self.remoteUserInfo.name];
}

**Comment by bjlinhong** [comment]
主叫发起呼叫, 被叫未接听前, 在主叫的大屏幕上显示的是本地视频, 所以此处理显示的名字, 也应该是主叫本地的.
在被叫接听后, 名字会根据大屏上显示的视频刷新, 
目前处理没有问题.
